/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssocieGerant {
  'id' : string,
  'nom' : string,
  'statut' : string,
  'remunerationAnnuelle' : number,
}
export interface Emprunt {
  'id' : string,
  'nom' : string,
  'tauxAnnuel' : number,
  'differeMois' : bigint,
  'dateDebut' : string,
  'montant' : number,
  'dureeMois' : bigint,
}
export interface Ingredient {
  'id' : string,
  'nom' : string,
  'seuilSecurite' : number,
  'stockInitial' : number,
  'famille' : [] | [string],
  'unite' : string,
  'prixUnitaireHT' : number,
}
export interface LigneAmortissement {
  'id' : string,
  'nom' : string,
  'coutTotal' : number,
  'dureeMois' : bigint,
}
export interface LigneFraisFixes {
  'nom' : string,
  'montantMensuelHorsRemu' : number,
  'montantMensuelAvecRemu' : number,
}
export interface MouvementStock {
  'id' : string,
  'motif' : string,
  'date' : string,
  'typeOp' : string,
  'quantite' : number,
  'ingredientId' : string,
}
export interface ParametresJuridiques {
  'regimeSocial' : string,
  'formeJuridique' : string,
  'regimeFiscal' : string,
}
export interface ParametresRentabilite {
  'nbSemainesSaison' : number,
  'nbClientsParSemaine' : number,
  'ticketMoyenHT' : number,
  'tauxFoodCostParCategorie' : Array<[string, number]>,
}
export interface Recette {
  'id' : string,
  'nom' : string,
  'categorie' : string,
  'tauxTVA' : number,
  'prixVenteTTC' : number,
  'consommablesHT' : number,
  'ingredients' : Array<RecetteIngredient>,
  'categorieTVA' : string,
}
export interface RecetteIngredient {
  'unite' : string,
  'quantite' : number,
  'ingredientId' : string,
}
export interface Salarie {
  'id' : string,
  'nom' : string,
  'salaireAnnuelBrut' : number,
  'poste' : string,
}
export interface VenteRecette {
  'id' : string,
  'recetteId' : string,
  'date' : string,
  'quantite' : number,
}
export interface _SERVICE {
  'createAmortissement' : ActorMethod<
    [string, number, bigint],
    LigneAmortissement
  >,
  'createAssocieGerant' : ActorMethod<[string, string, number], AssocieGerant>,
  'createEmprunt' : ActorMethod<
    [string, number, number, bigint, string, bigint],
    Emprunt
  >,
  'createIngredient' : ActorMethod<
    [string, string, number, number, number, [] | [string]],
    Ingredient
  >,
  'createMouvement' : ActorMethod<
    [string, string, string, number, string],
    MouvementStock
  >,
  'createRecette' : ActorMethod<
    [string, string, string, number, Array<RecetteIngredient>, number, number],
    Recette
  >,
  'createSalarie' : ActorMethod<[string, string, number], Salarie>,
  'createVente' : ActorMethod<[string, string, number], VenteRecette>,
  'deleteAmortissement' : ActorMethod<[string], boolean>,
  'deleteAssocieGerant' : ActorMethod<[string], boolean>,
  'deleteEmprunt' : ActorMethod<[string], boolean>,
  'deleteIngredient' : ActorMethod<[string], boolean>,
  'deleteMouvement' : ActorMethod<[string], boolean>,
  'deleteRecette' : ActorMethod<[string], boolean>,
  'deleteSalarie' : ActorMethod<[string], boolean>,
  'deleteVente' : ActorMethod<[string], boolean>,
  'getAmortissements' : ActorMethod<[], Array<LigneAmortissement>>,
  'getAssociesGerants' : ActorMethod<[], Array<AssocieGerant>>,
  'getEmprunts' : ActorMethod<[], Array<Emprunt>>,
  'getFamilles' : ActorMethod<[], Array<string>>,
  'getFraisFixes' : ActorMethod<[], Array<LigneFraisFixes>>,
  'getIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getJoursOuvertureParSemaine' : ActorMethod<[], number>,
  'getMixProduitParCategorie' : ActorMethod<[], Array<[string, number]>>,
  'getMouvementsStock' : ActorMethod<[], Array<MouvementStock>>,
  'getParametres' : ActorMethod<[], ParametresRentabilite>,
  'getParametresJuridiques' : ActorMethod<[], ParametresJuridiques>,
  'getRecettes' : ActorMethod<[], Array<Recette>>,
  'getSalaries' : ActorMethod<[], Array<Salarie>>,
  'getVentesRecettes' : ActorMethod<[], Array<VenteRecette>>,
  'saveFraisFixes' : ActorMethod<[Array<LigneFraisFixes>], boolean>,
  'saveJoursOuvertureParSemaine' : ActorMethod<[number], boolean>,
  'saveMixProduitParCategorie' : ActorMethod<
    [Array<[string, number]>],
    boolean
  >,
  'saveParametres' : ActorMethod<[ParametresRentabilite], boolean>,
  'saveParametresJuridiques' : ActorMethod<[ParametresJuridiques], boolean>,
  'setFamilles' : ActorMethod<[Array<string>], boolean>,
  'updateAmortissement' : ActorMethod<
    [string, string, number, bigint],
    boolean
  >,
  'updateAssocieGerant' : ActorMethod<
    [string, string, string, number],
    boolean
  >,
  'updateEmprunt' : ActorMethod<
    [string, string, number, number, bigint, string, bigint],
    boolean
  >,
  'updateIngredient' : ActorMethod<
    [string, string, string, number, number, number, [] | [string]],
    boolean
  >,
  'updateRecette' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      Array<RecetteIngredient>,
      number,
      number,
    ],
    boolean
  >,
  'updateSalarie' : ActorMethod<[string, string, string, number], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];