/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LigneAmortissement = IDL.Record({
  'id' : IDL.Text,
  'nom' : IDL.Text,
  'coutTotal' : IDL.Float64,
  'dureeMois' : IDL.Nat,
});
export const AssocieGerant = IDL.Record({
  'id' : IDL.Text,
  'nom' : IDL.Text,
  'statut' : IDL.Text,
  'remunerationAnnuelle' : IDL.Float64,
});
export const Emprunt = IDL.Record({
  'id' : IDL.Text,
  'nom' : IDL.Text,
  'tauxAnnuel' : IDL.Float64,
  'differeMois' : IDL.Nat,
  'dateDebut' : IDL.Text,
  'montant' : IDL.Float64,
  'dureeMois' : IDL.Nat,
});
export const Ingredient = IDL.Record({
  'id' : IDL.Text,
  'nom' : IDL.Text,
  'seuilSecurite' : IDL.Float64,
  'stockInitial' : IDL.Float64,
  'unite' : IDL.Text,
  'prixUnitaireHT' : IDL.Float64,
});
export const MouvementStock = IDL.Record({
  'id' : IDL.Text,
  'motif' : IDL.Text,
  'date' : IDL.Text,
  'typeOp' : IDL.Text,
  'quantite' : IDL.Float64,
  'ingredientId' : IDL.Text,
});
export const RecetteIngredient = IDL.Record({
  'unite' : IDL.Text,
  'quantite' : IDL.Float64,
  'ingredientId' : IDL.Text,
});
export const Recette = IDL.Record({
  'id' : IDL.Text,
  'nom' : IDL.Text,
  'categorie' : IDL.Text,
  'tauxTVA' : IDL.Float64,
  'prixVenteTTC' : IDL.Float64,
  'consommablesHT' : IDL.Float64,
  'ingredients' : IDL.Vec(RecetteIngredient),
  'categorieTVA' : IDL.Text,
});
export const Salarie = IDL.Record({
  'id' : IDL.Text,
  'nom' : IDL.Text,
  'salaireAnnuelBrut' : IDL.Float64,
  'poste' : IDL.Text,
});
export const VenteRecette = IDL.Record({
  'id' : IDL.Text,
  'recetteId' : IDL.Text,
  'date' : IDL.Text,
  'quantite' : IDL.Float64,
});
export const LigneFraisFixes = IDL.Record({
  'nom' : IDL.Text,
  'montantMensuelHorsRemu' : IDL.Float64,
  'montantMensuelAvecRemu' : IDL.Float64,
});
export const ParametresRentabilite = IDL.Record({
  'nbSemainesSaison' : IDL.Float64,
  'nbClientsParSemaine' : IDL.Float64,
  'ticketMoyenHT' : IDL.Float64,
  'tauxFoodCostParCategorie' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const ParametresJuridiques = IDL.Record({
  'regimeSocial' : IDL.Text,
  'formeJuridique' : IDL.Text,
  'regimeFiscal' : IDL.Text,
});

export const idlService = IDL.Service({
  'createAmortissement' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Nat],
      [LigneAmortissement],
      [],
    ),
  'createAssocieGerant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [AssocieGerant],
      [],
    ),
  'createEmprunt' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Nat, IDL.Text, IDL.Nat],
      [Emprunt],
      [],
    ),
  'createIngredient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [Ingredient],
      [],
    ),
  'createMouvement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [MouvementStock],
      [],
    ),
  'createRecette' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Vec(RecetteIngredient),
        IDL.Float64,
        IDL.Float64,
      ],
      [Recette],
      [],
    ),
  'createSalarie' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [Salarie], []),
  'createVente' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [VenteRecette],
      [],
    ),
  'deleteAmortissement' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteAssocieGerant' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteEmprunt' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteIngredient' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteMouvement' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteRecette' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteSalarie' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteVente' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAmortissements' : IDL.Func([], [IDL.Vec(LigneAmortissement)], ['query']),
  'getAssociesGerants' : IDL.Func([], [IDL.Vec(AssocieGerant)], ['query']),
  'getEmprunts' : IDL.Func([], [IDL.Vec(Emprunt)], ['query']),
  'getFraisFixes' : IDL.Func([], [IDL.Vec(LigneFraisFixes)], ['query']),
  'getIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getJoursOuvertureParSemaine' : IDL.Func([], [IDL.Float64], ['query']),
  'getMixProduitParCategorie' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getMouvementsStock' : IDL.Func([], [IDL.Vec(MouvementStock)], ['query']),
  'getParametres' : IDL.Func([], [ParametresRentabilite], ['query']),
  'getParametresJuridiques' : IDL.Func([], [ParametresJuridiques], ['query']),
  'getRecettes' : IDL.Func([], [IDL.Vec(Recette)], ['query']),
  'getSalaries' : IDL.Func([], [IDL.Vec(Salarie)], ['query']),
  'getVentesRecettes' : IDL.Func([], [IDL.Vec(VenteRecette)], ['query']),
  'saveFraisFixes' : IDL.Func([IDL.Vec(LigneFraisFixes)], [IDL.Bool], []),
  'saveJoursOuvertureParSemaine' : IDL.Func([IDL.Float64], [IDL.Bool], []),
  'saveMixProduitParCategorie' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      [IDL.Bool],
      [],
    ),
  'saveParametres' : IDL.Func([ParametresRentabilite], [IDL.Bool], []),
  'saveParametresJuridiques' : IDL.Func([ParametresJuridiques], [IDL.Bool], []),
  'updateAmortissement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updateAssocieGerant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'updateEmprunt' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Bool],
      [],
    ),
  'updateIngredient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'updateRecette' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Vec(RecetteIngredient),
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Bool],
      [],
    ),
  'updateSalarie' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LigneAmortissement = IDL.Record({
    'id' : IDL.Text,
    'nom' : IDL.Text,
    'coutTotal' : IDL.Float64,
    'dureeMois' : IDL.Nat,
  });
  const AssocieGerant = IDL.Record({
    'id' : IDL.Text,
    'nom' : IDL.Text,
    'statut' : IDL.Text,
    'remunerationAnnuelle' : IDL.Float64,
  });
  const Emprunt = IDL.Record({
    'id' : IDL.Text,
    'nom' : IDL.Text,
    'tauxAnnuel' : IDL.Float64,
    'differeMois' : IDL.Nat,
    'dateDebut' : IDL.Text,
    'montant' : IDL.Float64,
    'dureeMois' : IDL.Nat,
  });
  const Ingredient = IDL.Record({
    'id' : IDL.Text,
    'nom' : IDL.Text,
    'seuilSecurite' : IDL.Float64,
    'stockInitial' : IDL.Float64,
    'unite' : IDL.Text,
    'prixUnitaireHT' : IDL.Float64,
  });
  const MouvementStock = IDL.Record({
    'id' : IDL.Text,
    'motif' : IDL.Text,
    'date' : IDL.Text,
    'typeOp' : IDL.Text,
    'quantite' : IDL.Float64,
    'ingredientId' : IDL.Text,
  });
  const RecetteIngredient = IDL.Record({
    'unite' : IDL.Text,
    'quantite' : IDL.Float64,
    'ingredientId' : IDL.Text,
  });
  const Recette = IDL.Record({
    'id' : IDL.Text,
    'nom' : IDL.Text,
    'categorie' : IDL.Text,
    'tauxTVA' : IDL.Float64,
    'prixVenteTTC' : IDL.Float64,
    'consommablesHT' : IDL.Float64,
    'ingredients' : IDL.Vec(RecetteIngredient),
    'categorieTVA' : IDL.Text,
  });
  const Salarie = IDL.Record({
    'id' : IDL.Text,
    'nom' : IDL.Text,
    'salaireAnnuelBrut' : IDL.Float64,
    'poste' : IDL.Text,
  });
  const VenteRecette = IDL.Record({
    'id' : IDL.Text,
    'recetteId' : IDL.Text,
    'date' : IDL.Text,
    'quantite' : IDL.Float64,
  });
  const LigneFraisFixes = IDL.Record({
    'nom' : IDL.Text,
    'montantMensuelHorsRemu' : IDL.Float64,
    'montantMensuelAvecRemu' : IDL.Float64,
  });
  const ParametresRentabilite = IDL.Record({
    'nbSemainesSaison' : IDL.Float64,
    'nbClientsParSemaine' : IDL.Float64,
    'ticketMoyenHT' : IDL.Float64,
    'tauxFoodCostParCategorie' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const ParametresJuridiques = IDL.Record({
    'regimeSocial' : IDL.Text,
    'formeJuridique' : IDL.Text,
    'regimeFiscal' : IDL.Text,
  });
  
  return IDL.Service({
    'createAmortissement' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Nat],
        [LigneAmortissement],
        [],
      ),
    'createAssocieGerant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [AssocieGerant],
        [],
      ),
    'createEmprunt' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Nat, IDL.Text, IDL.Nat],
        [Emprunt],
        [],
      ),
    'createIngredient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [Ingredient],
        [],
      ),
    'createMouvement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [MouvementStock],
        [],
      ),
    'createRecette' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Vec(RecetteIngredient),
          IDL.Float64,
          IDL.Float64,
        ],
        [Recette],
        [],
      ),
    'createSalarie' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [Salarie],
        [],
      ),
    'createVente' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [VenteRecette],
        [],
      ),
    'deleteAmortissement' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteAssocieGerant' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteEmprunt' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteIngredient' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteMouvement' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteRecette' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteSalarie' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteVente' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAmortissements' : IDL.Func(
        [],
        [IDL.Vec(LigneAmortissement)],
        ['query'],
      ),
    'getAssociesGerants' : IDL.Func([], [IDL.Vec(AssocieGerant)], ['query']),
    'getEmprunts' : IDL.Func([], [IDL.Vec(Emprunt)], ['query']),
    'getFraisFixes' : IDL.Func([], [IDL.Vec(LigneFraisFixes)], ['query']),
    'getIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getJoursOuvertureParSemaine' : IDL.Func([], [IDL.Float64], ['query']),
    'getMixProduitParCategorie' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getMouvementsStock' : IDL.Func([], [IDL.Vec(MouvementStock)], ['query']),
    'getParametres' : IDL.Func([], [ParametresRentabilite], ['query']),
    'getParametresJuridiques' : IDL.Func([], [ParametresJuridiques], ['query']),
    'getRecettes' : IDL.Func([], [IDL.Vec(Recette)], ['query']),
    'getSalaries' : IDL.Func([], [IDL.Vec(Salarie)], ['query']),
    'getVentesRecettes' : IDL.Func([], [IDL.Vec(VenteRecette)], ['query']),
    'saveFraisFixes' : IDL.Func([IDL.Vec(LigneFraisFixes)], [IDL.Bool], []),
    'saveJoursOuvertureParSemaine' : IDL.Func([IDL.Float64], [IDL.Bool], []),
    'saveMixProduitParCategorie' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        [IDL.Bool],
        [],
      ),
    'saveParametres' : IDL.Func([ParametresRentabilite], [IDL.Bool], []),
    'saveParametresJuridiques' : IDL.Func(
        [ParametresJuridiques],
        [IDL.Bool],
        [],
      ),
    'updateAmortissement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateAssocieGerant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'updateEmprunt' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Bool],
        [],
      ),
    'updateIngredient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'updateRecette' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Vec(RecetteIngredient),
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Bool],
        [],
      ),
    'updateSalarie' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };