/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Emprunt {
    id: string;
    nom: string;
    tauxAnnuel: number;
    differeMois: bigint;
    dateDebut: string;
    montant: number;
    dureeMois: bigint;
}
export interface RecetteIngredient {
    unite: string;
    quantite: number;
    ingredientId: string;
}
export interface Recette {
    id: string;
    nom: string;
    categorie: string;
    tauxTVA: number;
    prixVenteTTC: number;
    consommablesHT: number;
    ingredients: Array<RecetteIngredient>;
    categorieTVA: string;
}
export interface VenteRecette {
    id: string;
    recetteId: string;
    date: string;
    quantite: number;
}
export interface ParametresRentabilite {
    nbSemainesSaison: number;
    nbClientsParSemaine: number;
    ticketMoyenHT: number;
    tauxFoodCostParCategorie: Array<[string, number]>;
}
export interface Ingredient {
    id: string;
    nom: string;
    seuilSecurite: number;
    stockInitial: number;
    famille?: string;
    unite: string;
    prixUnitaireHT: number;
}
export interface ParametresJuridiques {
    regimeSocial: string;
    formeJuridique: string;
    regimeFiscal: string;
}
export interface LigneAmortissement {
    id: string;
    nom: string;
    coutTotal: number;
    dureeMois: bigint;
}
export interface AssocieGerant {
    id: string;
    nom: string;
    statut: string;
    remunerationAnnuelle: number;
}
export interface LigneFraisFixes {
    nom: string;
    montantMensuelHorsRemu: number;
    montantMensuelAvecRemu: number;
}
export interface MouvementStock {
    id: string;
    motif: string;
    date: string;
    typeOp: string;
    quantite: number;
    ingredientId: string;
}
export interface Salarie {
    id: string;
    nom: string;
    salaireAnnuelBrut: number;
    poste: string;
}
export interface backendInterface {
    createAmortissement(nom: string, coutTotal: number, dureeMois: bigint): Promise<LigneAmortissement>;
    createAssocieGerant(nom: string, statut: string, remunerationAnnuelle: number): Promise<AssocieGerant>;
    createEmprunt(nom: string, montant: number, tauxAnnuel: number, dureeMois: bigint, dateDebut: string, differeMois: bigint): Promise<Emprunt>;
    createIngredient(nom: string, unite: string, prixUnitaireHT: number, seuilSecurite: number, stockInitial: number, famille: string | null): Promise<Ingredient>;
    createMouvement(ingredientId: string, date: string, typeOp: string, quantite: number, motif: string): Promise<MouvementStock>;
    createRecette(nom: string, categorie: string, categorieTVA: string, tauxTVA: number, ings: Array<RecetteIngredient>, consommablesHT: number, prixVenteTTC: number): Promise<Recette>;
    createSalarie(nom: string, poste: string, salaireAnnuelBrut: number): Promise<Salarie>;
    createVente(recetteId: string, date: string, quantite: number): Promise<VenteRecette>;
    deleteAmortissement(id: string): Promise<boolean>;
    deleteAssocieGerant(id: string): Promise<boolean>;
    deleteEmprunt(id: string): Promise<boolean>;
    deleteIngredient(id: string): Promise<boolean>;
    deleteMouvement(id: string): Promise<boolean>;
    deleteRecette(id: string): Promise<boolean>;
    deleteSalarie(id: string): Promise<boolean>;
    deleteVente(id: string): Promise<boolean>;
    getAmortissements(): Promise<Array<LigneAmortissement>>;
    getAssociesGerants(): Promise<Array<AssocieGerant>>;
    getEmprunts(): Promise<Array<Emprunt>>;
    getFamilles(): Promise<Array<string>>;
    getFraisFixes(): Promise<Array<LigneFraisFixes>>;
    getIngredients(): Promise<Array<Ingredient>>;
    getJoursOuvertureParSemaine(): Promise<number>;
    getMixProduitParCategorie(): Promise<Array<[string, number]>>;
    getMouvementsStock(): Promise<Array<MouvementStock>>;
    getParametres(): Promise<ParametresRentabilite>;
    getParametresJuridiques(): Promise<ParametresJuridiques>;
    getRecettes(): Promise<Array<Recette>>;
    getSalaries(): Promise<Array<Salarie>>;
    getVentesRecettes(): Promise<Array<VenteRecette>>;
    saveFraisFixes(lignes: Array<LigneFraisFixes>): Promise<boolean>;
    saveJoursOuvertureParSemaine(v: number): Promise<boolean>;
    saveMixProduitParCategorie(m: Array<[string, number]>): Promise<boolean>;
    saveParametres(p: ParametresRentabilite): Promise<boolean>;
    saveParametresJuridiques(p: ParametresJuridiques): Promise<boolean>;
    setFamilles(f: Array<string>): Promise<boolean>;
    updateAmortissement(id: string, nom: string, coutTotal: number, dureeMois: bigint): Promise<boolean>;
    updateAssocieGerant(id: string, nom: string, statut: string, remunerationAnnuelle: number): Promise<boolean>;
    updateEmprunt(id: string, nom: string, montant: number, tauxAnnuel: number, dureeMois: bigint, dateDebut: string, differeMois: bigint): Promise<boolean>;
    updateIngredient(id: string, nom: string, unite: string, prixUnitaireHT: number, seuilSecurite: number, stockInitial: number, famille: string | null): Promise<boolean>;
    updateRecette(id: string, nom: string, categorie: string, categorieTVA: string, tauxTVA: number, ings: Array<RecetteIngredient>, consommablesHT: number, prixVenteTTC: number): Promise<boolean>;
    updateSalarie(id: string, nom: string, poste: string, salaireAnnuelBrut: number): Promise<boolean>;
}
import type { Ingredient as _Ingredient } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAmortissement(arg0: string, arg1: number, arg2: bigint): Promise<LigneAmortissement> {
        if (this.processError) {
            try {
                const result = await this.actor.createAmortissement(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAmortissement(arg0, arg1, arg2);
            return result;
        }
    }
    async createAssocieGerant(arg0: string, arg1: string, arg2: number): Promise<AssocieGerant> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssocieGerant(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssocieGerant(arg0, arg1, arg2);
            return result;
        }
    }
    async createEmprunt(arg0: string, arg1: number, arg2: number, arg3: bigint, arg4: string, arg5: bigint): Promise<Emprunt> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmprunt(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmprunt(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createIngredient(arg0: string, arg1: string, arg2: number, arg3: number, arg4: number, arg5: string | null): Promise<Ingredient> {
        if (this.processError) {
            try {
                const result = await this.actor.createIngredient(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Ingredient_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIngredient(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Ingredient_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMouvement(arg0: string, arg1: string, arg2: string, arg3: number, arg4: string): Promise<MouvementStock> {
        if (this.processError) {
            try {
                const result = await this.actor.createMouvement(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMouvement(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createRecette(arg0: string, arg1: string, arg2: string, arg3: number, arg4: Array<RecetteIngredient>, arg5: number, arg6: number): Promise<Recette> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecette(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecette(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createSalarie(arg0: string, arg1: string, arg2: number): Promise<Salarie> {
        if (this.processError) {
            try {
                const result = await this.actor.createSalarie(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSalarie(arg0, arg1, arg2);
            return result;
        }
    }
    async createVente(arg0: string, arg1: string, arg2: number): Promise<VenteRecette> {
        if (this.processError) {
            try {
                const result = await this.actor.createVente(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVente(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteAmortissement(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAmortissement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAmortissement(arg0);
            return result;
        }
    }
    async deleteAssocieGerant(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssocieGerant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssocieGerant(arg0);
            return result;
        }
    }
    async deleteEmprunt(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmprunt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmprunt(arg0);
            return result;
        }
    }
    async deleteIngredient(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIngredient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIngredient(arg0);
            return result;
        }
    }
    async deleteMouvement(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMouvement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMouvement(arg0);
            return result;
        }
    }
    async deleteRecette(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecette(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecette(arg0);
            return result;
        }
    }
    async deleteSalarie(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSalarie(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSalarie(arg0);
            return result;
        }
    }
    async deleteVente(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVente(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVente(arg0);
            return result;
        }
    }
    async getAmortissements(): Promise<Array<LigneAmortissement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAmortissements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAmortissements();
            return result;
        }
    }
    async getAssociesGerants(): Promise<Array<AssocieGerant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssociesGerants();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssociesGerants();
            return result;
        }
    }
    async getEmprunts(): Promise<Array<Emprunt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmprunts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmprunts();
            return result;
        }
    }
    async getFamilles(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFamilles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFamilles();
            return result;
        }
    }
    async getFraisFixes(): Promise<Array<LigneFraisFixes>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFraisFixes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFraisFixes();
            return result;
        }
    }
    async getIngredients(): Promise<Array<Ingredient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIngredients();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIngredients();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJoursOuvertureParSemaine(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getJoursOuvertureParSemaine();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJoursOuvertureParSemaine();
            return result;
        }
    }
    async getMixProduitParCategorie(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMixProduitParCategorie();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMixProduitParCategorie();
            return result;
        }
    }
    async getMouvementsStock(): Promise<Array<MouvementStock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMouvementsStock();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMouvementsStock();
            return result;
        }
    }
    async getParametres(): Promise<ParametresRentabilite> {
        if (this.processError) {
            try {
                const result = await this.actor.getParametres();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParametres();
            return result;
        }
    }
    async getParametresJuridiques(): Promise<ParametresJuridiques> {
        if (this.processError) {
            try {
                const result = await this.actor.getParametresJuridiques();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParametresJuridiques();
            return result;
        }
    }
    async getRecettes(): Promise<Array<Recette>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecettes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecettes();
            return result;
        }
    }
    async getSalaries(): Promise<Array<Salarie>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalaries();
            return result;
        }
    }
    async getVentesRecettes(): Promise<Array<VenteRecette>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVentesRecettes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVentesRecettes();
            return result;
        }
    }
    async saveFraisFixes(arg0: Array<LigneFraisFixes>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFraisFixes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFraisFixes(arg0);
            return result;
        }
    }
    async saveJoursOuvertureParSemaine(arg0: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveJoursOuvertureParSemaine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveJoursOuvertureParSemaine(arg0);
            return result;
        }
    }
    async saveMixProduitParCategorie(arg0: Array<[string, number]>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMixProduitParCategorie(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMixProduitParCategorie(arg0);
            return result;
        }
    }
    async saveParametres(arg0: ParametresRentabilite): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveParametres(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveParametres(arg0);
            return result;
        }
    }
    async saveParametresJuridiques(arg0: ParametresJuridiques): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveParametresJuridiques(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveParametresJuridiques(arg0);
            return result;
        }
    }
    async setFamilles(arg0: Array<string>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setFamilles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFamilles(arg0);
            return result;
        }
    }
    async updateAmortissement(arg0: string, arg1: string, arg2: number, arg3: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAmortissement(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAmortissement(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateAssocieGerant(arg0: string, arg1: string, arg2: string, arg3: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssocieGerant(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssocieGerant(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateEmprunt(arg0: string, arg1: string, arg2: number, arg3: number, arg4: bigint, arg5: string, arg6: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmprunt(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmprunt(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateIngredient(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIngredient(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIngredient(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateRecette(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: Array<RecetteIngredient>, arg6: number, arg7: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecette(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecette(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateSalarie(arg0: string, arg1: string, arg2: string, arg3: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalarie(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalarie(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Ingredient_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ingredient): Ingredient {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    nom: string;
    seuilSecurite: number;
    stockInitial: number;
    famille: [] | [string];
    unite: string;
    prixUnitaireHT: number;
}): {
    id: string;
    nom: string;
    seuilSecurite: number;
    stockInitial: number;
    famille?: string;
    unite: string;
    prixUnitaireHT: number;
} {
    return {
        id: value.id,
        nom: value.nom,
        seuilSecurite: value.seuilSecurite,
        stockInitial: value.stockInitial,
        famille: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.famille)),
        unite: value.unite,
        prixUnitaireHT: value.prixUnitaireHT
    };
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ingredient>): Array<Ingredient> {
    return value.map((x)=>from_candid_Ingredient_n2(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
